
package fi.jyu.webapp.clients.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Disk", targetNamespace = "http://test")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Disk {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDiskbyId", targetNamespace = "http://test", className = "test.GetDiskbyId")
    @ResponseWrapper(localName = "getDiskbyIdResponse", targetNamespace = "http://test", className = "test.GetDiskbyIdResponse")
    @Action(input = "http://test/Disk/getDiskbyIdRequest", output = "http://test/Disk/getDiskbyIdResponse")
    public String getDiskbyId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDisks", targetNamespace = "http://test", className = "test.GetDisks")
    @ResponseWrapper(localName = "getDisksResponse", targetNamespace = "http://test", className = "test.GetDisksResponse")
    @Action(input = "http://test/Disk/getDisksRequest", output = "http://test/Disk/getDisksResponse")
    public String getDisks();

}
