
package fi.jyu.webapp.clients.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DiskService", targetNamespace = "http://test", wsdlLocation = "http://localhost:9000/?wsdl")
public class DiskService
    extends Service
{

    private final static URL DISKSERVICE_WSDL_LOCATION;
    private final static WebServiceException DISKSERVICE_EXCEPTION;
    private final static QName DISKSERVICE_QNAME = new QName("http://test", "DiskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://webstorage-soap.herokuapp.com/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISKSERVICE_WSDL_LOCATION = url;
        DISKSERVICE_EXCEPTION = e;
    }

    public DiskService() {
        super(__getWsdlLocation(), DISKSERVICE_QNAME);
    }

    public DiskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISKSERVICE_QNAME, features);
    }

    public DiskService(URL wsdlLocation) {
        super(wsdlLocation, DISKSERVICE_QNAME);
    }

    public DiskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISKSERVICE_QNAME, features);
    }

    public DiskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DiskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Disk
     */
    @WebEndpoint(name = "DiskPort")
    public Disk getDiskPort() {
        return super.getPort(new QName("http://test", "DiskPort"), Disk.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Disk
     */
    @WebEndpoint(name = "DiskPort")
    public Disk getDiskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test", "DiskPort"), Disk.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISKSERVICE_EXCEPTION!= null) {
            throw DISKSERVICE_EXCEPTION;
        }
        return DISKSERVICE_WSDL_LOCATION;
    }

}
