
package fi.jyu.webapp.clients.gamasystem;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExchangeRatesSoap", targetNamespace = "http://www.gama-system.com/webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExchangeRatesSoap {


    /**
     * Method returns an XML formatted string containing exchange rates for the specified bank and currency that are between specified values.
     * 
     * @param strCurrency
     * @param dcmHigh
     * @param intRank
     * @param strBank
     * @param dcmLow
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRatesByValueXML", action = "http://www.gama-system.com/webservices/GetExchangeRatesByValueXML")
    @WebResult(name = "GetExchangeRatesByValueXMLResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "GetExchangeRatesByValueXML", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesByValueXML")
    @ResponseWrapper(localName = "GetExchangeRatesByValueXMLResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesByValueXMLResponse")
    public String getExchangeRatesByValueXML(
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "dcmLow", targetNamespace = "http://www.gama-system.com/webservices")
        BigDecimal dcmLow,
        @WebParam(name = "dcmHigh", targetNamespace = "http://www.gama-system.com/webservices")
        BigDecimal dcmHigh,
        @WebParam(name = "intRank", targetNamespace = "http://www.gama-system.com/webservices")
        int intRank);

    /**
     * Method returns an XML formatted string containing exchange rates for the specified bank and currency that are between specified dates.
     * 
     * @param strDateLow
     * @param strCurrency
     * @param strBank
     * @param strDateHigh
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRatesByDateXML", action = "http://www.gama-system.com/webservices/GetExchangeRatesByDateXML")
    @WebResult(name = "GetExchangeRatesByDateXMLResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "GetExchangeRatesByDateXML", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesByDateXML")
    @ResponseWrapper(localName = "GetExchangeRatesByDateXMLResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesByDateXMLResponse")
    public String getExchangeRatesByDateXML(
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "strDateLow", targetNamespace = "http://www.gama-system.com/webservices")
        String strDateLow,
        @WebParam(name = "strDateHigh", targetNamespace = "http://www.gama-system.com/webservices")
        String strDateHigh);

    /**
     * Method returns an XML formatted string containing exchange rates for the specified bank and date.
     * 
     * @param strBank
     * @param strDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRatesXML", action = "http://www.gama-system.com/webservices/GetExchangeRatesXML")
    @WebResult(name = "GetExchangeRatesXMLResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "GetExchangeRatesXML", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesXML")
    @ResponseWrapper(localName = "GetExchangeRatesXMLResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesXMLResponse")
    public String getExchangeRatesXML(
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strDate", targetNamespace = "http://www.gama-system.com/webservices")
        String strDate);

    /**
     * Method returns an XML formatted string containing current exchange rates for the specified bank.
     * 
     * @param strBank
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCurrentExchangeRatesXML", action = "http://www.gama-system.com/webservices/GetCurrentExchangeRatesXML")
    @WebResult(name = "GetCurrentExchangeRatesXMLResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "GetCurrentExchangeRatesXML", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetCurrentExchangeRatesXML")
    @ResponseWrapper(localName = "GetCurrentExchangeRatesXMLResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetCurrentExchangeRatesXMLResponse")
    public String getCurrentExchangeRatesXML(
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank);

    /**
     * Method returns XML schema (XSD) in which all XML formatted exchange rate information is in.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRatesXMLSchema", action = "http://www.gama-system.com/webservices/GetExchangeRatesXMLSchema")
    @WebResult(name = "GetExchangeRatesXMLSchemaResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "GetExchangeRatesXMLSchema", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesXMLSchema")
    @ResponseWrapper(localName = "GetExchangeRatesXMLSchemaResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRatesXMLSchemaResponse")
    public String getExchangeRatesXMLSchema();

    /**
     * Method returns current specified exchange rate for the specified bank and currency.
     * 
     * @param strCurrency
     * @param intRank
     * @param strBank
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetCurrentExchangeRate", action = "http://www.gama-system.com/webservices/GetCurrentExchangeRate")
    @WebResult(name = "GetCurrentExchangeRateResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "GetCurrentExchangeRate", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetCurrentExchangeRate")
    @ResponseWrapper(localName = "GetCurrentExchangeRateResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetCurrentExchangeRateResponse")
    public BigDecimal getCurrentExchangeRate(
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "intRank", targetNamespace = "http://www.gama-system.com/webservices")
        int intRank);

    /**
     * Method returns specified exchange rate for the specified bank, date and currency.
     * 
     * @param strCurrency
     * @param intRank
     * @param strBank
     * @param strDate
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetExchangeRate", action = "http://www.gama-system.com/webservices/GetExchangeRate")
    @WebResult(name = "GetExchangeRateResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "GetExchangeRate", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRate")
    @ResponseWrapper(localName = "GetExchangeRateResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.GetExchangeRateResponse")
    public BigDecimal getExchangeRate(
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "strDate", targetNamespace = "http://www.gama-system.com/webservices")
        String strDate,
        @WebParam(name = "intRank", targetNamespace = "http://www.gama-system.com/webservices")
        int intRank);

    /**
     * Method converts the specified value of foreign currency to EUR.
     * 
     * @param strCurrency
     * @param intRank
     * @param strBank
     * @param strDate
     * @param dcmValue
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "ConvertToEUR", action = "http://www.gama-system.com/webservices/ConvertToEUR")
    @WebResult(name = "ConvertToEURResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "ConvertToEUR", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.ConvertToEUR")
    @ResponseWrapper(localName = "ConvertToEURResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.ConvertToEURResponse")
    public BigDecimal convertToEUR(
        @WebParam(name = "dcmValue", targetNamespace = "http://www.gama-system.com/webservices")
        BigDecimal dcmValue,
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "strDate", targetNamespace = "http://www.gama-system.com/webservices")
        String strDate,
        @WebParam(name = "intRank", targetNamespace = "http://www.gama-system.com/webservices")
        int intRank);

    /**
     * Method converts the specified value of EUR to foreign currency.
     * 
     * @param strCurrency
     * @param intRank
     * @param strBank
     * @param strDate
     * @param dcmEUR
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "ConvertToForeign", action = "http://www.gama-system.com/webservices/ConvertToForeign")
    @WebResult(name = "ConvertToForeignResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "ConvertToForeign", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.ConvertToForeign")
    @ResponseWrapper(localName = "ConvertToForeignResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.ConvertToForeignResponse")
    public BigDecimal convertToForeign(
        @WebParam(name = "dcmEUR", targetNamespace = "http://www.gama-system.com/webservices")
        BigDecimal dcmEUR,
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "strDate", targetNamespace = "http://www.gama-system.com/webservices")
        String strDate,
        @WebParam(name = "intRank", targetNamespace = "http://www.gama-system.com/webservices")
        int intRank);

    /**
     * Method converts the current specified value of foreign currency to EUR.
     * 
     * @param strCurrency
     * @param intRank
     * @param strBank
     * @param dcmValue
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "CurrentConvertToEUR", action = "http://www.gama-system.com/webservices/CurrentConvertToEUR")
    @WebResult(name = "CurrentConvertToEURResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "CurrentConvertToEUR", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.CurrentConvertToEUR")
    @ResponseWrapper(localName = "CurrentConvertToEURResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.CurrentConvertToEURResponse")
    public BigDecimal currentConvertToEUR(
        @WebParam(name = "dcmValue", targetNamespace = "http://www.gama-system.com/webservices")
        BigDecimal dcmValue,
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "intRank", targetNamespace = "http://www.gama-system.com/webservices")
        int intRank);

    /**
     * Method converts the specified value of EUR to current foreign currency.
     * 
     * @param strCurrency
     * @param intRank
     * @param strBank
     * @param dcmEUR
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "CurrentConvertToForeign", action = "http://www.gama-system.com/webservices/CurrentConvertToForeign")
    @WebResult(name = "CurrentConvertToForeignResult", targetNamespace = "http://www.gama-system.com/webservices")
    @RequestWrapper(localName = "CurrentConvertToForeign", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.CurrentConvertToForeign")
    @ResponseWrapper(localName = "CurrentConvertToForeignResponse", targetNamespace = "http://www.gama-system.com/webservices", className = "com.gama_system.webservices.CurrentConvertToForeignResponse")
    public BigDecimal currentConvertToForeign(
        @WebParam(name = "dcmEUR", targetNamespace = "http://www.gama-system.com/webservices")
        BigDecimal dcmEUR,
        @WebParam(name = "strBank", targetNamespace = "http://www.gama-system.com/webservices")
        String strBank,
        @WebParam(name = "strCurrency", targetNamespace = "http://www.gama-system.com/webservices")
        String strCurrency,
        @WebParam(name = "intRank", targetNamespace = "http://www.gama-system.com/webservices")
        int intRank);

}
